---
title: "Trabajo y presentación final — Panel corto con función Cobb–Douglas"
subtitle: "econometria II pes"
author: "Autores: Pedro Monzón, Mario Castro, Kevin Molina "
format: pdf
editor: visual
---

::: callout-note
**Nota rápida sobre panel corto.** En panel corto $T$ pequeño y $n$ moderado/grande), las inferencias son más fiables con errores estándar agrupados por unidad (o dos vías si $T$ es suficiente). También es útil contrastar FE vs RE (Hausman) y evaluar exogeneidad estricta, heterogeneidad inobservada y dependencia en sección cruzada.
:::

# Introducción

Este proyecto busca estudiar las diferencias del crecimiento tecnológico$\ A$ sobre el PIB real entre regiones utlizando un panel de datos entre 2015 y 2020. Utilizando datos de panel de la Penn World Table 11.0.

**Problemas:**

-   ¿Cuál es la elasticidad de producción respecto al empleo $L$, la del capital $K$ y la productividad total de los factores $A_0$ en una función tipo Cobb–Douglas para una muestra en panel corto?

-   ¿Existe diferencia respecto al la tecnología de las regiones del mundo?

<!-- -->

-   ¿Cual es el componente de tecnología para Centromérica, y

-   ¿Cuales son sus elásticidades?

**Justificación:**

Conocer las elasticidades de la producción respecto al nivel medir elasticidades permite conocer la eficiencia en el aprovechamiento de los recursos de un país, así como retornos de escala, relevantes en la orientación decisiones de política y e inversión en el entorno internacional y macroeconómico, el uso de información tipo panel permite el uso de técnicas para controlar la heterogeneidad inobservada de los individuos.

**Objetivo:**

-   Estimar y contrastar modelos (Pooled, FE, RE, Mundlak) y seleccionar el especificación óptima para describir $Q$ en función de $L$ y $K$, con controles de heterogeneidad y diagnóstico completo. productividad total de los factores

# Modelo (teoría)

Función Cobb–Douglas agregada: $$Q_{it} = A_{it} K_{it}^{\alpha} L_{it}^{\beta}e^{u_{it}},$$ que en logaritmos se linealiza como: $$ln Q_{it} = A_0 + \alpha ln L_{it} + \beta ln K_{it} + c_{i} + \epsilon_{it}$$

-   $c_i$: efectos (inobservados) específicos de unidad.
-   Retornos a escala: $\alpha + \beta$.

Hipótesis clave: - Exogeneidad estricta de regresores (o al menos de $ln L$, $ln K$).

\- Heterogeneidad inobservada potencialmente correlacionada con regresores FE o Mundlak.

Para las pruebas usaremos el siguiente que incluye controles : $$ln Q_{it} = \beta_1 + \beta_2 ln L_{it} + \beta_3 ln K_{it} + c_{i} + \epsilon_{it}$$

# Metodología

**Datos.** Importados desde `datat_panel_corto.xlsx`. Se asume estructura:

\- PIB real, rgndp, Output-side GDP at chained PPPs (2017 USD).

\- Capital, rnna, Servicios del capital (2017 USD).

\- Empleo, emp, Número de personas empleadas.

\- Control, rkna, irr, Capital humano y tasa de depreciación.

**Estrategia empírica.**

**Pruebas:**

LM Breusch–Pagan (no pooled vs pooled),

Hausman (FE vs RE),

Mundlak (significancia de medias por id),

Heterocedasticidad (White).

Autocorrelación Wooldridge AR(1),

# Resultados

## Significancia

Hipotesis:

$$H_0: \beta_k=0\,\,\,vs\,\,\,H_1: \beta_k\neq0\,\,\,\forall\,k=1,..,K$$

| variable         | Coeficiente | Estadistico - t | p-valor |
|------------------|-------------|-----------------|---------|
| $\beta_1$        | 10.82457    | 199.8994        | 0.0000  |
| $\beta_3$ LNRKNA | 1.094484    | 3.717484        | 0.0002  |
| $\beta_2$ LNEMP  | 0.939899    | 50.39413        | 0.0000  |

Interpretación:

-   En el primero modelo con MCO todas las variables rechazan la hipotesis nula con lo cual se puede infiere significancia , además el signo de capital y trabajo son positivos el esperado por la teoría económíca.
-   El que se haya pasado esta prueba nos indica que nuestro modelo es solido y tiene sentido economico ya que este no contradice la teoría., gracias a esto podemos realizar las siguientes pruebas econometricas.

## Breusch–Pagan

Hipotesis:

$$H_0: \sigma_{\mu}^2=0\,\,\,vs\,\,\,H_1: \sigma_{\mu}^2\neq0$$

Resultados:

| variable   | Estadistico - $\chi^2$ | p-valor |
|------------|------------------------|---------|
| $\sigma^2$ | 2048.162               | 0.0000  |

Interpretación:

-   p-valor es menor a 0.001 lo cual implica que se rechaza $H_0$ a cualquier nivel de significancia. Se descarta que el modelo sea pooled ya que la prueba infiere que pueden existir efectos aleatorios significativos.
-   Sabiendo que nuestro modelo no es pooled podemos realizar las pruebas para saber si es un panel con efectos fijos o con efectos aleatorios.

## Haussman

Hipotesis: $$H_0: Cov(x_{it},μ_{i})=0\,\,\,vs\,\,\,H_1: Cov(x_{it}, μ_{i})\neq0$$

Resultados:

| test                 | Estadistico - $\chi^2$ | p-valor |
|----------------------|------------------------|---------|
| Cross section-random | 27.806061              | 0.0000  |

Interpretación:

-   Se rechaza $H_0$ con la cual podemos inferir que RE son inconcistente por lo que para nuestro modelo usaremos FE.
-   Sabiendo que nuestro modelo tiene efectos fijos podemos ir por 3 caminos eliminarlos, controlarlos o usar CRE. Como ingresaremos varias variables dummys que son constantes no podemos elimiarlos debido a que esta información es crucial para nuestro modelo. por lo que no iremos por CRE por lo que es necesario realizar la prueba Munlak.

## Heterocedasticidad y Autocorrelación:

Se optó por realizar las estimaciones utilizando errores estándar robustos de White con corrección por sección cruzada ("White cross-section"), sacrificando así la eficiencia para contar con consistencia ante la presencia de heterocedasticidad y autocorrelación en los errores.

## Munlak:

Se procedió a aplicar al modelo panel, la prueba de Mundlak en la que se incluye los promedios a lo largo del tiempo de las variables explicativas, capturando de esta manera la heterogeneidad individual, y evaluando la significancia de los coeficientes.

Resultados (Resumidos):

| Variable                         | Coeificiente | Estadístico - t | P-valor |
|----------------------------------|--------------|-----------------|---------|
| $\ C$                            | 0.571558     | 19.25503        | 0.0000  |
| $\ ln(rnna)$                     | -1.181668    | -5.028303       | 0.0040  |
| $\ ln((emp)$                     | 0.33718      | 0.630803        | 0.5559  |
| $\ ln(rkna)$                     | 1.761365     | 7.256737        | 0.0008  |
| $\ ln(irr)$                      | 0.149121     | 0.660938        | 0.5379  |
| $\ australia\,and\,new\,zealand$ | 0.507438     | 170.6943        | 0.0000  |
| $\ western\,europe$              | 0.337306     | 145.3728        | 0.0000  |
| $\ eastern\,asia$                | 0.205481     | 30.71888        | 0.0000  |
| $\ northern\,america$            | 0.514339     | 140.9615        | 0.0000  |
| $\ eastern\,asia$                | 0.154359     | 11.93129        | 0.0001  |
| $\ northern\,africa$             | 0.427063     | 50.04812        | 0.0000  |
| $\ ln(rnna)\,promedio$           | 2.05137      | 8.75873         | 0.0000  |
| $\ ln(empb)\,promedio$           | -0.221616    | -0.414674       | 0.0000  |
| $\ ln(rknab)\,promedio$          | -3.096272    | -12.4321        | 0.0000  |
| $\ ln(irr)\,promedio$            | 0.164315     | 0.73733         | 0.0000  |

El ajuste Mundlak funciona bajo la hipótesis $\ H_0: \gamma =0$, en la que los promedios de las regresoras no explican $\ u_i$ lo que implica ausencia de correlación entre ambas.

Interpretación: En este caso se determinó que sí existe dicha correlación y se conserva como modelo final la misma especificación como Modelo, puesto que permite controlar la heterogeneidad detectada.

# Prueba de Wald: Rendimientos constantes a escala para

Se realizó la prueba de w

# Modelo Final

Después del análisis se determinó optar el modelo de Mundlak con matriz de convarianzas robustas tipo white. Esto permite tener un modelo que relaja el supuesto de homocedasticidad y de autocorrelación, permitiendo consistencia en los parámetros, con ayuda del control de la heterogeneidad:

$$
\begin{aligned}
lnQ &= 0.5716 
- 1.1817\,\ln(\text{rnna})
+ 0.3372\,\ln(\text{empleo})\\
&\quad + 1.7614\,\ln(\text{rkna})
+ 0.1491\,\ln(\text{irr}) \\
&\quad - 0.0065\,\text{Caribbean}
+ 0.3759\,\text{Middle Africa}
+ 0.1119\,\text{Southern Europe}\\
&\quad + 0.1351\,\text{Western Asia}
+ 0.1031\,\text{South America} \\
&\quad + 0.5074\,\text{Australia \& New Zealand}
+ 0.3373\,\text{Western Europe}
+ 0.1643\,\text{Eastern Africa}\\
&\quad + 0.0707\,\text{Western Africa}
+ 0.0862\,\text{Southern Asia} \\
&\quad + 0.2055\,\text{Eastern Asia}
+ 0.5143\,\text{Northern America}
- 0.0607\,\text{South Eastern Asia}\\
&\quad + 0.2037\,\text{Southern Africa}
+ 0.2005\,\text{Northern Europe} \\
&\quad + 0.4271\,\text{Northern Africa}
+ 0.3308\,\text{Melanesia}
- 0.2397\,\text{Central Asia} \\
&\quad + 2.0514\,\ln(\text{rnna promedio})
- 0.2216\,\ln(\text{empleo promedio})
- 3.0963\,\ln(\text{rkna promedio}) \\
&\quad + 0.1643\,\ln(\text{irr promedio}) + \varepsilon
\end{aligned}
$$

::: pagebreak :::

# Referencias

-   Wooldridge, J. M. (2010). *Econometric Analysis of Cross Section and Panel Data*. MIT Press.
-   Baltagi, B. H. (2021). *Econometric Analysis of Panel Data* (6ª ed.). Springer.
-   Mundlak, Y. (1978). *On the Pooling of Time Series and Cross Section Data*. Econometrica, 46(1), 69–85.
-   Arellano, M. (2003). *Panel Data Econometrics*. Oxford University Press.

::: pagebreak :::

# Apéndice

## Tabla de modelo munlak completo

| Variable                         | Coeificiente | Estadístico - t | P-valor |
|----------------------------------|--------------|-----------------|---------|
| $\ C$                            | 0.571558     | 19.25503        | 0.0000  |
| $\ ln(rnna)$                     | -1.181668    | -5.028303       | 0.0040  |
| $\ ln((emp)$                     | 0.33718      | 0.630803        | 0.5559  |
| $\ ln(rkna)$                     | 1.761365     | 7.256737        | 0.0008  |
| $\ ln(irr)$                      | 0.149121     | 0.660938        | 0.5379  |
| $\ caribbean$                    | -0.006518    | -1.289447       | 0.2537  |
| $\ middle\,africa$               | 0.375896     | 43.79931        | 0.0000  |
| $\ southern\,europe$             | 0.111903     | 39.62774        | 0.0000  |
| $\ western\,asia$                | 0.13506      | 28.84038        | 0.0000  |
| $\ south\,america$               | 0.103056     | 8.378035        | 0.0004  |
| $\ australia\,and\,new\,zealand$ | 0.507438     | 170.6943        | 0.0000  |
| $\ western\,europe$              | 0.337306     | 145.3728        | 0.0000  |
| $\ eastern\,africa$              | 0.164271     | 19.65421        | 0.0000  |
| $\ western\,africa$              | 0.07068      | 6.18675         | 0.0016  |
| $\ southern\,asia$               | 0.086194     | 11.46297        | 0.0001  |
| $\ eastern\,asia$                | 0.205481     | 30.71888        | 0.0000  |
| $\ northern\,america$            | 0.514339     | 140.9615        | 0.0000  |
| $\ south\,eastern\,asia$         | -0.060717    | -13.48968       | 0.0000  |
| $\ southern\,africa$             | 0.203666     | 79.33278        | 0.0000  |
| $\ eastern\,asia$                | 0.154359     | 11.93129        | 0.0001  |
| $\ northern\,europe$             | 0.200516     | 59.88689        | 0.0000  |
| $\ northern\,africa$             | 0.427063     | 50.04812        | 0.0000  |
| $\ central\,asia$                | -0.23973     | -25.50089       | 0.0000  |
| $\ ln(rnna)\,promedio$           | 2.05137      | 8.75873         | 0.0000  |
| $\ ln(empb)\,promedio$           | -0.221616    | -0.414674       | 0.0000  |
| $\ ln(rknab)\,promedio$          | -3.096272    | -12.4321        | 0.0000  |
| $\ ln(irr)\,promedio$            | 0.164315     | 0.73733         | 0.0000  |

::: pagebreak :::
